# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Primer workflow MIDU

on:
  push:
    branches: ["main"]

jobs:
  learning:
    runs-on: ubuntu-latest

    steps:
      - name: "Hola mundo"
        run: echo 'Hello world'
      - name: Dime la fecha
        run: date
      - name: Muestra el contenido del directorio
        run: ls -la
